// <auto-generated />
using System;
using Entities.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebAPI.Migrations
{
    [DbContext(typeof(RepoContext))]
    [Migration("20210701090935_Modif-StationCarburant")]
    partial class ModifStationCarburant
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Carburant", b =>
                {
                    b.Property<Guid>("IdCa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_CA");

                    b.Property<string>("CodeEu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StationServiceIdSt")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdCa");

                    b.HasIndex("StationServiceIdSt");

                    b.ToTable("Carburants");
                });

            modelBuilder.Entity("Entities.Models.Marque", b =>
                {
                    b.Property<Guid>("IdMa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_MA");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMa");

                    b.ToTable("Marque");
                });

            modelBuilder.Entity("Entities.Models.Releve", b =>
                {
                    b.Property<Guid>("IdRe")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_RE");

                    b.Property<Guid>("CarburantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,5)");

                    b.Property<Guid>("StationServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdRe");

                    b.HasIndex(new[] { "CarburantId" }, "IX_Releves_CarburantId");

                    b.HasIndex(new[] { "StationServiceId" }, "IX_Releves_StationServiceId");

                    b.HasIndex(new[] { "UserId" }, "IX_Releves_UserId");

                    b.ToTable("Releves");
                });

            modelBuilder.Entity("Entities.Models.StationService", b =>
                {
                    b.Property<Guid>("IdSt")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_ST");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MarqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSt");

                    b.HasIndex(new[] { "MarqueId" }, "IX_StationServices_MarqueId");

                    b.ToTable("StationServices");
                });

            modelBuilder.Entity("Entities.Models.StationServiceCarburant", b =>
                {
                    b.Property<Guid>("CarburantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StationServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CarburantId", "StationServiceId");

                    b.HasIndex(new[] { "StationServiceId" }, "IX_StationServiceCarburants_StationServiceId");

                    b.ToTable("StationServiceCarburants");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<Guid>("IdUs")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id_US");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUs");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Models.UserFavouritesStationsService", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FavouriteStationsServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "FavouriteStationsServiceId");

                    b.HasIndex(new[] { "FavouriteStationsServiceId" }, "IX_UserFavouritesStationsServices_FavouriteStationsServiceId");

                    b.ToTable("UserFavouritesStationsServices");
                });

            modelBuilder.Entity("Entities.Models.Carburant", b =>
                {
                    b.HasOne("Entities.Models.StationService", null)
                        .WithMany("Carburants")
                        .HasForeignKey("StationServiceIdSt");
                });

            modelBuilder.Entity("Entities.Models.Releve", b =>
                {
                    b.HasOne("Entities.Models.Carburant", "Carburant")
                        .WithMany("Releves")
                        .HasForeignKey("CarburantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.StationService", "StationService")
                        .WithMany("Releves")
                        .HasForeignKey("StationServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Releves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carburant");

                    b.Navigation("StationService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.StationService", b =>
                {
                    b.HasOne("Entities.Models.Marque", "Marque")
                        .WithMany("StationServices")
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marque");
                });

            modelBuilder.Entity("Entities.Models.StationServiceCarburant", b =>
                {
                    b.HasOne("Entities.Models.Carburant", "Carburant")
                        .WithMany("StationServiceCarburants")
                        .HasForeignKey("CarburantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.StationService", "StationService")
                        .WithMany("StationServiceCarburants")
                        .HasForeignKey("StationServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carburant");

                    b.Navigation("StationService");
                });

            modelBuilder.Entity("Entities.Models.UserFavouritesStationsService", b =>
                {
                    b.HasOne("Entities.Models.StationService", "FavouriteStationsService")
                        .WithMany("UserFavouritesStationsServices")
                        .HasForeignKey("FavouriteStationsServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("UserFavouritesStationsServices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavouriteStationsService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Carburant", b =>
                {
                    b.Navigation("Releves");

                    b.Navigation("StationServiceCarburants");
                });

            modelBuilder.Entity("Entities.Models.Marque", b =>
                {
                    b.Navigation("StationServices");
                });

            modelBuilder.Entity("Entities.Models.StationService", b =>
                {
                    b.Navigation("Carburants");

                    b.Navigation("Releves");

                    b.Navigation("StationServiceCarburants");

                    b.Navigation("UserFavouritesStationsServices");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("Releves");

                    b.Navigation("UserFavouritesStationsServices");
                });
#pragma warning restore 612, 618
        }
    }
}
